React & Redux group project - Space Travelers' Hub
Emmanuelaaron/spaceships pull request #58
Opened 2021-10-07 22:29 UTC by mariordgez

In this Project, we worked with real live data from the SpaceX API. We build a web application for a company that provides commercial and scientific space travel services. The application will allow users to book rockets, dragons and join selected space missions.

Rockets /Dragons

The Rockets section displays a list of all available SpaceX rockets. Users can book each rocket by clicking the reservation button or cancel the previously made booking. The same layout is used to form the Dragons section.
Rockets /Dragons

The Rockets section displays a list of all available SpaceX rockets. Users can book each rocket by clicking the reservation button or cancel the previously made booking. The same layout is used to form the Dragons section Space Travelers Hub.
Here is the wire-frame for the Rockets/Dragons page:
![image](https://user-images.githubusercontent.com/78693143/136470632-fa2202cb-4853-4dd9-baa0-8c025139df92.png)

Missions

The Missions section displays a list of current missions along with their brief description and participation status. There is also a button next to each mission that allows users to join the selected mission or leave the mission the user joined earlier. 

![image](https://user-images.githubusercontent.com/78693143/136470686-c53c55e3-f5a1-4aaf-852d-ef633342b590.png)

My Profile

The My Profile section displays all reserved rockets, dragons and space missions.
We made sure to only dispatch the fetch actions once and do not add data to store on every re-render (i.e. when changing views / using navigation).

Hope you like our project and have a wonderful day!!

2021-10-07 23:24 UTC, mke2111 requested changes
### Hey @mariordgez & @Emmanuelaaron & @enionsouza, 

**This is a great project you have going on, well-done lads**.  Most of your implementations are spot-on. Cheers! 👍🏽 💯 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-07 23:29 UTC, mke2111 commented on src/components/Missions.js
> +        </tbody>
- [x] For this group project, Rockets/Dragons and Missions should use the React conditional rendering syntax. You have implemented this perfectly in the components/Dragons.js and in components/Rockets.js, but it is missing in the components/Missions.js file. You could implement this in many ways, one of them being:
`{missions && missions.map((mission) => (`   --------------on line 28

2021-10-07 23:32 UTC, mke2111 commented on src/components/MyProfile.js
> +};
OPTIONAL

- The My Profile section can be enhanced by adding a placeholder message when the "My Missions" or "My Rockets" lists are empty (no missions joined or no rockets reserved).
- The My Profile section can be enhanced by adding the "Cancel reservation" and "Leave Mission" buttons to the lists here. Clicking them should dispatch the actions you have already used in the main Rockets and Missions sections.
- The My Profile section can be enhanced by adding the "Read more" button for each mission and rocket. Upon click, it should open a corresponding Wikipedia page in a new tab. NOTE - you need to get that extra Wikipedia URL from the API's payload.

2021-10-07 23:34 UTC, mke2111 commented on README.md
> +</p>
OPTIONAL

- [ ] Add the live link to the deployed version of your app to this file.

2021-10-08 00:01 UTC, mariordgez commented on src/components/Missions.js
> +        </tbody>
Missions are now rendered using react conditional render syntax

2021-10-08 17:04 UTC, BrianSammit approved these changes
# STATUS: APROVED :green_circle: :clap: 

Hello team 👋, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![200w](https://user-images.githubusercontent.com/64173189/136595719-19a5275a-f3d2-4110-aab2-cd3eb4cba5d0.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-08 17:06 UTC, merged